CREATE TABLE IF NOT EXISTS notification (
    id      bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint       NOT NULL,
    message text         NOT NULL,
    is_read boolean      NOT NULL DEFAULT false,
    sent_at timestamp(6) NOT NULL
);

-- Every read is "this user's notifications, newest first".
CREATE INDEX IF NOT EXISTS idx_notification_user_id_sent_at ON notification (user_id, sent_at DESC);
