-- Baseline of the schema as Hibernate's ddl-auto=update left it.
-- Existing databases are baselined at this version and skip it (see
-- spring.flyway.baseline-on-migrate); a fresh database runs it to create the schema.
-- The unique constraint keeps Hibernate's generated name so both paths end up identical.
CREATE TABLE IF NOT EXISTS users (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      varchar(255) NOT NULL,
    full_name  varchar(255) NOT NULL,
    password   varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
);
