-- Baseline of the schema as Hibernate's ddl-auto=update left it.
-- Existing databases are baselined at this version and skip it (see
-- spring.flyway.baseline-on-migrate); a fresh database runs it to create the schema.
CREATE TABLE IF NOT EXISTS post (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    text         NOT NULL,
    user_id    bigint       NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS post_likes (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    bigint       NOT NULL,
    user_id    bigint       NOT NULL,
    created_at timestamp(6) NOT NULL
);
